version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  build:
    docker:
      - image: cirrusci/flutter:beta

    steps:
      - checkout
      - run: mv ./lib/amplifyconfiguration.dart.example ./lib/amplifyconfiguration.dart
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test --coverage --coverage-path=~/coverage/lcov.info
      - codecov/upload:
          file: ~/coverage/lcov.info